version: "3.7"

x-shared-config:
  base: &base
    # image: beevelop/ionic:v2023.10.1
    build: "./docker"
    image: ionic
    tmpfs:
      - /tmp
    user: ":1420"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - ANDROID_ADB_SERVER_ADDRESS=${ANDROID_ADB_SERVER_ADDRESS:-host.docker.internal}
    stdin_open: true
    tty: true
    ports:
      - 8100:8100
      - 35729:35729
    volumes:
      - ./:/app:cached
      - ~/.gradle/cache:/root/.gradle/
      # - ./node_modules:/app/node_modules
    working_dir: "/app"
    extra_hosts:
      - "host.docker.internal:host-gateway"

services:
  android_live_reload:
    <<: *base
    container_name: ionic_rangers_android
    command: ionic cap run android -l --external --consolelogs --skip-plugins eslint
    environment: 
     - "VITE_BACKEND_API_URL=${LOCAL_BACKEND_API_URL}"
    network_mode: host

  app:
    <<: *base
    container_name: ionic_rangers_webapp
    command: ionic serve -c --external --consolelogs

  app_host:
    <<: *base
    container_name: ionic_rangers_webapp_host_mode
    command: ionic serve -c --external --consolelogs
    environment: 
     - "VITE_BACKEND_API_URL=${LOCAL_BACKEND_API_URL}"
    network_mode: host
    
  shell:
    <<: *base
    container_name: ionic_rangers_shell
    command: /bin/sh

  shell_host:
    <<: *base
    container_name: ionic_rangers_shell_host_mode
    environment: 
     - "VITE_BACKEND_API_URL=${LOCAL_BACKEND_API_URL}"
    command: /bin/sh
    network_mode: host

networks:
  default:
    external: true
    name: "${DOCKER_RANGERS_NETWORK:-rangers}"